const fs = require('fs/promises')
const mongodb = require('mongodb')
const crypto = require('crypto')


let cachedClient = undefined
let cachedDb = undefined
async function getDatabase() {
    if (cachedClient) {
        return cachedDb // already connected so use the cache
    }
    cachedClient = new mongodb.MongoClient('mongodb+srv://60106430:M59955155m%24@cluster0.czdr4xk.mongodb.net/infs3201_winter2026?retryWrites=true&w=majority&appName=Cluster0')
    await cachedClient.connect()
    cachedDb = cachedClient.db('infs3201_winter2026')
    return cachedDb
}

async function disconnectDatabase() {
    if (!cachedClient) {
        return
    }
    cachedClient.close()
}

/**
 * Return a list of all employees loaded from the storage.
 * @returns {Array<{ employeeId: string, name: string, phone: string }>} List of employees
 */
async function getAllEmployees() {
    let db = await getDatabase()
    let employeesCollection = db.collection('employees')
    let result = employeesCollection.find()
    return result.toArray()
}

/**
 * Find a single employee given their ID number.
 * @param {string} empId 
 * @returns {{ employeeId: string, name: string, phone: string }|undefined}
 */
async function findEmployee(empId) {
    let db = await getDatabase()
    let employeesCollection = db.collection('employees')
    let result = employeesCollection.findOne({_id: new mongodb.ObjectId(empId)})
    return result
}

/**
 * Get a single shift given the shiftId
 * @param {string} shiftId 
 * @returns {{shiftId:string, date:string, startTime:string, endTime:string}|undefined}
 */
async function findShift(shiftId) {
    let db = await getDatabase()
    let shiftCollection = db.collection('shifts')
    let shift = shiftCollection.findOne({shiftId: shiftId})
    return shift
}

/**
 * Get a list of shiftIDs for an employee.
 * @param {string} empId 
 * @returns {Array<{string}>}
 */
async function getEmployeeShifts(empId) {
    let db = await getDatabase()
    
    let empObjectId = new mongodb.ObjectId(empId)
    let shiftCollection = db.collection('shifts')
    let shiftDetails = shiftCollection.find(
        {employees: empObjectId}
    ).toArray()

    return shiftDetails
}

/**
 * Add a new employee record to the system. The empId is automatically generated based
 * on the next available ID number from what is already in the file.
 * @param {{name:string, phone:string}} emp 
 */
async function addEmployeeRecord(emp) {
    let db = await getDatabase()
    let employees = db.collection('employees')
    let aggregateResult = await employees.aggregate([
        {
            $project: {
            employeeNum: {
                $toInt: {
                $substr: ["$employeeId", 1, -1]
                }
            }
            }
        },
        {
            $group: {
            _id: null,
            maxEmployeeNum: { $max: "$employeeNum" }
            }
        }
    ]).toArray()

    let maxId = aggregateResult[0].maxEmployeeNum
    emp.employeeId = `E${String(maxId+1).padStart(3,'0')}`
    await employees.insertOne(emp)
}

async function updateEmployee(empDetails) {
    let db = await getDatabase()
    let employees = db.collection('employees')
    let empMongoId = new mongodb.ObjectId(empDetails.employeeId)
    console.log(empDetails)
    await employees.updateOne(
        {
            _id: empMongoId
        }, 
        {
            $set: {
                name: empDetails.employeeName,
                phone: empDetails.employeePhone
            }
        }
    )
    return "OK"
}

async function checkCredentials(username, password) {
    let hashedPassword = crypto.createHash('sha256')
        .update(password)
        .digest('hex')
    let db = await getDatabase()
    let users = db.collection('users')
    let result = await users.findOne({
        user: username,
        password: hashedPassword
    })
    return result != null
}

/**
 * Create a new session given the session id (generated by the above layer).  The session object
 * in the database will have an id and an expiry field... data can be arbitrary.
 * @param {*} sessionId 
 * @param {*} timeout 
 * @param {*} data 
 */
async function createSession(sessionId, timeout, data) {
    let db = await getDatabase()
    let sessions = db.collection('sessions')
    const expiresAt = new Date(Date.now() + timeout * 1000)
    await sessions.insertOne({
        id: sessionId,
        expiry: expiresAt,
        data: data
    })
}

/**
 * Get the data associated with a session.
 * @param {*} sessionId 
 * @returns The data associated with a session or null if the data or session does not exist.
 */
async function getSessionData(sessionId) {
    let db = await getDatabase()
    let sessions = db.collection('sessions')
    let result = await sessions.findOne({
        id: sessionId
    })
    if (result) {
        return result.data
    }
    return null
}

/**
 * Update the timestamp in the database for the session.
 * 
 * @param {*} sessionId 
 * @param {*} seconds 
 * @returns true if the operation was successful.
 */
async function extendSession(sessionId, seconds) {
    let db = await getDatabase()
    let sessions = db.collection('sessions')
    let newExpiry = new Date(Date.now() + seconds*1000)
    let result = await sessions.updateOne({id: sessionId}, {$set: {expiry: newExpiry}})
    return result.modifiedCount === 1
}

/**
 * Record an event to the security log
 * 
 * @param {*} username 
 * @param {*} url 
 * @param {*} method 
 */
async function logEvent(username, url, method) {
    let db = await getDatabase()
    let securityLog = db.collection('security_log')
    let timestamp = new Date(Date.now())
    securityLog.insertOne({
        timestamp,
        username,
        url,
        method
    })
}
/**
 * Find one user by username.
 * @param {string} username
 * @returns {Object|null}
 */
async function findUser(username) {
    let db = await getDatabase()
    let users = db.collection('users')
    let result = await users.findOne({ user: username })
    return result
}

/**
 * Increase failed login attempts by 1.
 * @param {string} username
 * @returns {number} updated failed attempts
 */
async function incrementFailedLogin(username) {
    let db = await getDatabase()
    let users = db.collection('users')

    await users.updateOne(
        { user: username },
        { $inc: { failedLoginAttempts: 1 } }
    )

    let updatedUser = await users.findOne({ user: username })
    return updatedUser.failedLoginAttempts
}

/**
 * Reset failed login attempts to 0.
 * @param {string} username
 */
async function resetFailedLogin(username) {
    let db = await getDatabase()
    let users = db.collection('users')

    await users.updateOne(
        { user: username },
        { $set: { failedLoginAttempts: 0 } }
    )
}

/**
 * Lock a user account.
 * @param {string} username
 */
async function lockUserAccount(username) {
    let db = await getDatabase()
    let users = db.collection('users')

    await users.updateOne(
        { user: username },
        { $set: { disabled: true } }
    )
}
module.exports = {
    getAllEmployees, findEmployee,
    findShift, getEmployeeShifts,
    addEmployeeRecord,
    disconnectDatabase, findEmployee, updateEmployee,
    checkCredentials, createSession, getSessionData, extendSession, logEvent,
    findUser, incrementFailedLogin, resetFailedLogin, lockUserAccount
}